apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-app
  labels:
    app: reverse-proxy-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008
  selector:
    app: reverse-proxy-app

